name: Lint and check
on: [ pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      # Run ruff linter
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1
      
      # Run ruff format
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1
        with:
          args: 'format --check'

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: '3.x'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # rich is optional at runtime, but install it so autoland's
          # optional import is type checked.
          pip install '.[dev,rich]'
      - name: Run mypy
        run: mypy src
